### PR TITLE
Fix table item editing

### LINKED ISSUE #17: Translations changes not exported correctly
When you add language or edit an existing language and you export the file the new strings or changed strings aren't exported but it keeps the oldest.

### PR DESCRIPTION
**Pull request by mlorenzano**
This PR fix #17.

### CODE REVIEW

File: ElcoLinguist/src/LanguagesModel.cpp [hunk 1]
```diff
@@ -56,6 +56,20 @@ QVector<Language> LanguagesModel::languages() const noexcept
     return ret;
 }
 
+bool LanguagesModel::setData(const QModelIndex &index, const QVariant &value, int role)
+{
+    Q_UNUSED(role)
+
+    auto it = item(index.row(), index.column());
+    auto oldText = it->text();
+    auto text = value.toString();
```
Comment (AndreaRicchi) [inline ElcoLinguist/src/LanguagesModel.cpp]: These variables should be defined as `const`.
